import { t } from '@/infrastructure/locales'
export const CATEGORIES = [
  { value: 'all', label: t('pages.help.categories.all') },
  { value: 'account', label: t('pages.help.categories.account') },
  { value: 'usage', label: t('pages.help.categories.usage') },
  { value: 'security', label: t('pages.help.categories.security') },
  { value: 'troubleshooting', label: t('pages.help.categories.troubleshooting') },
  { value: 'other', label: t('pages.help.categories.other') },
]

export const FAQ_DATA = [
  {
    id: '0',
    question: t('pages.help.faq.0.question'),
    answer: t('pages.help.faq.0.answer'),
    category: 'other',
    views: 1250,
  },
  {
    id: '1',
    question: t('pages.help.faq.1.question'),
    answer: t('pages.help.faq.1.answer'),
    category: 'account',
    views: 1250,
  },
  {
    id: '2',
    question: t('pages.help.faq.2.question'),
    answer: t('pages.help.faq.2.answer'),
    category: 'usage',
    views: 986,
  },
  {
    id: '3',
    question: t('pages.help.faq.3.question'),
    answer: t('pages.help.faq.3.answer'),
    category: 'usage',
    views: 2340,
  },
  {
    id: '5',
    question: t('pages.help.faq.5.question'),
    answer: t('pages.help.faq.5.answer'),
    category: 'other',
    views: 3210,
  },
  {
    id: '7',
    question: t('pages.help.faq.7.question'),
    answer: t('pages.help.faq.7.answer'),
    category: 'security',
    views: 1420,
  },
  {
    id: '8',
    question: t('pages.help.faq.8.question'),
    answer: t('pages.help.faq.8.answer'),
    category: 'account',
    views: 4560,
  },
  {
    id: '9',
    question: t('pages.help.faq.9.question'),
    answer: t('pages.help.faq.9.answer'),
    category: 'other',
    views: 2890,
  },
  {
    id: '10',
    question: t('pages.help.faq.10.question'),
    answer: t('pages.help.faq.10.answer'),
    category: 'usage',
    views: 1680,
  },
  {
    id: '11',
    question: t('pages.help.faq.11.question'),
    answer: t('pages.help.faq.11.answer'),
    category: 'usage',
    views: 3120,
  },
  {
    id: '12',
    question: t('pages.help.faq.12.question'),
    answer: t('pages.help.faq.12.answer'),
    category: 'troubleshooting',
    views: 890,
  },
  {
    id: '13',
    question: t('pages.help.faq.13.question'),
    answer: t('pages.help.faq.13.answer'),
    category: 'troubleshooting',
    views: 2010,
  },
  {
    id: '14',
    question: t('pages.help.faq.14.question'),
    answer: t('pages.help.faq.14.answer'),
    category: 'other',
    views: 1740,
  },
  {
    id: '15',
    question: t('pages.help.faq.15.question'),
    answer: t('pages.help.faq.15.answer'),
    category: 'other',
    views: 1320,
  },
]
